version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Vurolock
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
